### ISSUE TITLE
In need for some clarifications :)

### ISSUE THREAD

**Issue by diasdavid** [whyrusleeping/go-multistream#1]
I think I get your logic, if I understood correctly, once you get a valid protocol, you pass the channel responsibility to an handler and only once that segment is finished, the handler will return the channel to the main loop where it is going to look for another proto, right?

I'm just not getting why I'm not getting a "na" as a response for non handled protocols:
https://github.com/whyrusleeping/go-multistream/blob/master/multistream.go#L95

**Comment by whyrusleeping** [comment]
multistream only handles a single protocol per connection. You connect, set your protocol and pass full responsibility on to the handler, once the handler takes control, multistream will never again touch that connection.

The "na" means "not available" as defined here: https://github.com/jbenet/multistream/tree/master/multistream-select#protocol

**Comment by diasdavid** [comment]
I'm not sure of what I'm doing it wrong, but I can't get "na" as a response, or any of the protocols available registered as handlers. 

Did you use this script to test: https://gist.github.com/whyrusleeping/e64fee1ae94061009223 ?

I've used netcat and https://www.npmjs.com/package/length-prefixed-message to write to the tcp stream for the "/cats" and "ls", but I could only get as far as receiving the protocol header "/multistream/version1.0.0"

**Comment by whyrusleeping** [comment]
@diasdavid youre doing the appropriate varint prefixed newline delimited strings, right?

**Comment by whyrusleeping** [comment]
every message must be:
```
<varint(len s)><s>\n
```

**Comment by jbenet** [comment]
@diasdavid did you test with https://github.com/whyrusleeping/mss-nc ? (i havent yet)

**Comment by diasdavid** [comment]
@jbenet thanks, with mss-nc works well

Was hoping that that https://github.com/sorribas/length-prefixed-message/blob/master/index.js#L1 would work since it is using varint also to describe the length, but something is being different. Investigating.

**Comment by whyrusleeping** [comment]
@diasdavid dont forget the trailing newline! its not counted as part of the length prefix.

**Comment by jbenet** [comment]
@whyrusleeping 
> its not counted as part of the length prefix.

why not? it should be, so varint msg writers are easier to think about.

**Comment by whyrusleeping** [comment]
fixed
